# Generated by Django 5.0.7 on 2024-08-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
