# Generated by Django 5.0.7 on 2024-08-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingCompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=255)),
                ('year_of_passing', models.IntegerField()),
                ('preferred_branch', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'UpcomingCompanyDetails',
            },
        ),
    ]
