# Generated by Django 5.0.7 on 2024-08-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDashboard', '0003_delete_category_delete_mode_delete_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('subject_one', models.CharField(max_length=255)),
                ('subject_two', models.CharField(max_length=255)),
                ('subject_three', models.CharField(max_length=255)),
                ('subject_four', models.CharField(max_length=255)),
                ('subject_five', models.CharField(max_length=255)),
                ('subject_six', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Curriculums',
            },
        ),
    ]
